resources:
  - ./../../apps/doorbell_app

patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
           name: DEVICE_MODE
           value: "Signaler"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
           name: DEVICE_ID
           value: "device-106"
    target:
      kind: Deployment
      namespace: workloads
      name: doorbell-app
